"""add_history_tables

Revision ID: c9e54939e25d
Revises: f1d9572bfaeb
Create Date: 2025-05-29 15:49:02.330344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9e54939e25d'
down_revision: Union[str, None] = 'f1d9572bfaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=True),
    sa.Column('output_summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_entries_action_type'), 'history_entries', ['action_type'], unique=False)
    op.create_index(op.f('ix_history_entries_id'), 'history_entries', ['id'], unique=False)
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.drop_column('users', 'facebook_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.drop_index(op.f('ix_history_entries_id'), table_name='history_entries')
    op.drop_index(op.f('ix_history_entries_action_type'), table_name='history_entries')
    op.drop_table('history_entries')
    # ### end Alembic commands ###
